// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    get: (function(_this) {
      return function(user, callback) {
        return callback(user);
      };
    })(this),
    save: (function(_this) {
      return function(id, callback) {
        return callback(id);
      };
    })(this)
  };

}).call(this);
